# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.252
neo_version_range=[21.1.0,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Mod
mod_id=surveyor
mod_name=Surveyor Map Framework
mod_description=Unified API, networking, and save data for map mods.
mod_license=LGPL-3.0-or-later
mod_version=1.2.4+1.21-neoforge
mod_group_id=folk.sisby
mod_authors=Sisby folk. Contributions by Ampflower, falkreon, jaskarth, Garden System. NeoForge port by Darkona
mod_sources=https://github.com/sisby-folk/surveyor
archive_name=surveyor-neoforge
